name: 내 맘대로 이름 변경

on:
  workflow_dispatch:

jobs:
  job-name-and-unique-identifier:
    runs-on: ubuntu-24.04
    steps:
      - name: alias Come on
        run: echo "Hello from an inline bash script in a GitHub Action Workflow!"
